### ISSUE TITLE
No Mongodb URI

### ISSUE THREAD

**Issue by kirerellim** [johnhelmuth/fate-bot#1]
You probably don't touch this anymore, but if you do, I'm getting the following errors when trying to run this after following instructions.

[2019-09-02T12_56_31_158Z-debug.log](https://github.com/johnhelmuth/fate-bot/files/3564642/2019-09-02T12_56_31_158Z-debug.log)

![image](https://user-images.githubusercontent.com/39993026/64093217-5de37480-cd0c-11e9-9fa7-fd42d8b7e2fa.png)

and its referencing this file

{
  "mongo": {
    "comment": "Where's your database? (mongo.url can be overwritten by the MONGODB_URI environment variable.)",
    "url": "mongodb+srv://kirerellim:<password>@fate-nzrxr.mongodb.net/test?retryWrites=true&w=majority"
  },
  "bot": {
    "comment": [
      "Set these from information on https://discordapp.com/developers/applications/me page for your application",
      "bot.token can be overwritten by the DISCORD_BOT_TOKEN environment variable.",
      "bot.client_id can be overwritten by the DISCORD_CLIENT_ID environment variable."
    ],
    "token": "NjE2NTE2MTY1NDA1MjQ1NDYw.XWduSg.k0QaRjiOu1-rmdlVfsG8umCHWR8",
    "client_id": "616516165405245460"
  },
  "dispatch": {
    "comment": "What character determines a given message is a command to the bot",
    "prefix": "!"
  },
  "diceroller": {
    "comment": "default dice specification, used when no specification is given.",
    "default": "4df"
  },
  "charsheet": {
    "comment": "Fate Character sheet skill list formatting.  Fate Core, pyramid should be true, Fate Accelerated,probably false.",
    "pyramid": true
  }
}

**Comment by Amaylia** [comment]
Where is that file located?  Looking at the readme, it is supposed to be in `./src/libs/config/prod.json`.

**Comment by kirerellim** [comment]
That is accurate, it just references it from index file

**Comment by Amaylia** [comment]
I don't really see a problem with the mongodb url code, and it loads it fine for me given the config that you are using, however, there are several other keys missing in the config that probably need to be added to the https://github.com/johnhelmuth/fate-bot/blob/master/src/libs/config/prod.dist.json file.

The keys that I had to add were:
* `app_domain`
* `amqp.url`
* `bot.client_secret`

The full config structure needed to start the app should look like this:
```
{
    "app_domain": "<Insert Domain for web app portion of the bot here>",
    "amqp": {
        "url":"<Insert RabbitMQ URI Here>"
    },
    "mongo": {
        "comment": "Where's your database? (mongo.url can be overwritten by the MONGODB_URI environment variable.)",
        "url": "mongodb+srv://kirerellim:YourPasswordHere@fate-nzrxr.mongodb.net/test?retryWrites=true&w=majority"
    },
    "bot": {
        "comment": [
            "Set these from information on https://discordapp.com/developers/applications/me page for your application",
            "bot.token can be overwritten by the DISCORD_BOT_TOKEN environment variable.",
            "bot.client_id can be overwritten by the DISCORD_CLIENT_ID environment variable."
        ],
        "token": "<Insert Bot Token Here>",
        "client_id": "<Insert Client ID Here>",
        "client_secret": "<Insert Client Secret Here>"
    },
    "dispatch": {
        "comment": "What character determines a given message is a command to the bot",
        "prefix": "!"
    },
    "diceroller": {
        "comment": "default dice specification, used when no specification is given.",
        "default": "4df"
    },
    "charsheet": {
        "comment": "Fate Character sheet skill list formatting. Fate Core, pyramid should be true, Fate Accelerated,probably false.",
        "pyramid": true
    }
}
```

**Comment by Amaylia** [comment]
Also, you may want to remove the DB password in your initial post.

**Comment by kirerellim** [comment]
Looks like this might just beyond my knowledge scope then lol I don't know anything about RabbitMQ or the app_domain, was hoping it would be mostly plug and play with minor modifications ><

**Comment by Amaylia** [comment]
You should be able to run just the bot without RabbitMQ, `npm run start:bot`.

You just won't have the Web UI then, which means you won't need app_domain to be anything valid either.

Edit: Actually, I take the app_domain part back, Discord still needs to be able to contact the bot.

**Comment by kirerellim** [comment]
Where would you find the app_domain then, if you don't mind me asking?

Edit: never mind, it just throws another error anyways, expected amqp: or ampqs: lol

**Comment by Amaylia** [comment]
I forked a copy and removed the amqp (that's RabbitMQ) requirement.  https://github.com/Amaylia/fate-bot.  I'll make RabbitMQ optional for the Web UI as well when I have some more time and see if I can't merge it back into this code base.

**Comment by kirerellim** [comment]
Well, it got further than before! I changed Mongo, token, client, and secret client as before. It responded with this:

![image](https://user-images.githubusercontent.com/39993026/64141821-68f6dd00-cdbe-11e9-94bd-b94144aafe89.png)

**Comment by Amaylia** [comment]
It looks like a permissions error with your mongodb service.  You might see if you can grant it the permissions it needs.

**Comment by Amaylia** [comment]
Were you able to figure things out with MongoDB?  Also, if you want some help on discord, my handle is the same as my username here with a `#0001` at the end.

**Comment by kirerellim** [comment]
Not yet, been working sense last response. I did glance at mongodb info but username is set up as admin and I don't see what other permissions I might need

**Comment by Amaylia** [comment]
By default, mongoDB has no built-in users, just built-in roles, so it's possible the user "admin" just wasn't given the proper roles.  The error message in your screenshot says that it doesn't have the `listIndexes` permission for the `sessions` database, I think.  You should be able to connect to your db and run a `db.getUser("admin")` command, and check that the roles granted to that user give it access to the "sessions" database.

You can refer to https://docs.mongodb.com/manual/reference/built-in-roles/ for a list of roles that you might need.  
To add roles to your user: https://docs.mongodb.com/manual/reference/method/db.grantRolesToUser/#db.grantRolesToUser

**Comment by kirerellim** [comment]
Well to make the link I had to make a user and password and I gave it atlas admin powers. But I tried making a custom role with all available powers and giving that user that roll and when I get home I'll give that a shot

**Comment by johnhelmuth** [comment]
I cut back on the functionality of Fate-bot so that it no longer requires a backend database of any kind... it is only a dice roller now.

Closing this issue because it's old and no longer an issue with the current code.

Maybe somebody I will resurrect the character sheet functionality, etc, etc, and tune up the documentation to make it easier to run.
